import ts from "npm:typescript@5.9.3";

const program = ts.createProgram(["./lib/elem.ts"], {
  target: ts.ScriptTarget.Latest,
  lib: ["lib.dom.d.ts", "lib.esnext.d.ts"],
});
const sourceFile = program.getSourceFile("./lib/elem.ts");
if (!sourceFile) throw new Error("Could not find elem.ts");

const checker = program.getTypeChecker();

const symbol = checker.resolveName("_SVGTags", sourceFile, ts.SymbolFlags.Type, false);
if (!symbol) throw new Error();
const type = checker.getDeclaredTypeOfSymbol(symbol);
if (!type.isUnion()) throw new Error();
const tags = type.types
  .filter(t => t.isStringLiteral())
  .map(t => t.value)
  .toSorted();

await Deno.writeTextFile(
  "./lib/$svg-tags.ts",
  `// generated by _gen/svg-tags.gen.ts <3
export const SVG_TAG_LIST = ${JSON.stringify(tags)};
`,
);
